"""Supply-chain contract for the wheel-only sealed Ava runtime."""

from __future__ import annotations

import base64
import csv
import hashlib
import io
import json
import os
import re
import stat
import subprocess
import sys
import zipfile
from pathlib import Path, PurePosixPath

import pytest
from ava_extensions.evals.relationship import release_attestation as release_contract

ROOT = Path(__file__).resolve().parents[2]
REQUIREMENTS = ROOT / "deploy/runtime/ava-runtime-requirements.v1.txt"
DOCOPT_WHEEL = ROOT / "deploy/runtime/wheels/docopt-0.6.2-py2.py3-none-any.whl"
PYTHON_RUNTIME = ROOT / "deploy/runtime/ava-python-runtime.v1.json"
UV_LOCK = ROOT / "uv.lock"
WHEELHOUSE_MANIFEST = ROOT / "deploy/runtime/ava-runtime-wheelhouse.v1.json"
WHEELHOUSE_GENERATOR = ROOT / "scripts/generate-runtime-wheelhouse-manifest.py"
DOCOPT_SDIST_SHA256 = "49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491"
DOCOPT_WHEEL_SHA256 = "6d6eabf5974d0b72899f74ecb6ae84f0d436ca0f7b3037ffc7b9a8a0790a6813"
DOCOPT_MODULE_SHA256 = (
    "44c650ebd833d852c8731fa3f0c5759506309622300e4c1954a540d78572cc54"
)
EXPORT_ARGUMENTS = (
    "--no-config",
    "export",
    "--frozen",
    "--no-default-groups",
    "--extra",
    "server",
    "--extra",
    "speech",
    "--extra",
    "dashboard",
    "--extra",
    "inference-cloud",
    "--extra",
    "framework-comparison",
    "--no-emit-project",
    "--no-emit-local",
    "--no-annotate",
)

EXPECTED_PYTHON_RUNTIME = {
    "archive": {
        "member_count": 4522,
        "regular_file_bytes": 97_688_071,
        "regular_file_count": 3474,
        "sealed_relative_path": ".ava-artifacts/python-runtime.tar.gz",
        "sha256": "d480f5d5878910ecbae212bf23bd7c25d7b209eb8cf5e98823c977384d272e88",
        "size": 34_075_380,
        "symlink_count": 1048,
        "url": (
            "https://releases.astral.sh/github/python-build-standalone/releases/"
            "download/20260510/cpython-3.12.13%2B20260510-x86_64-unknown-linux-"
            "gnu-install_only_stripped.tar.gz"
        ),
    },
    "build": "20260510",
    "implementation": "cpython",
    "platform": "x86_64-unknown-linux-gnu",
    "schema": "ava.python-runtime-source/v1",
    "version": "3.12.13",
}


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def test_python_runtime_source_pin_is_closed_and_content_addressed() -> None:
    raw = PYTHON_RUNTIME.read_bytes()
    assert raw.endswith(b"\n")
    assert json.loads(raw) == EXPECTED_PYTHON_RUNTIME
    assert len(EXPECTED_PYTHON_RUNTIME["archive"]["sha256"]) == 64
    assert EXPECTED_PYTHON_RUNTIME["archive"]["sealed_relative_path"].startswith(
        ".ava-artifacts/"
    )


def test_runtime_requirements_are_the_lock_export_plus_the_audited_wheel() -> None:
    committed_lines = REQUIREMENTS.read_text(encoding="utf-8").splitlines()
    assert committed_lines[:2] == [
        "# This file was autogenerated by uv via the following command:",
        "#    uv "
        + " ".join(EXPORT_ARGUMENTS)
        + " --output-file deploy/runtime/ava-runtime-requirements.v1.txt",
    ]
    generated = subprocess.run(
        ["uv", *EXPORT_ARGUMENTS, "--no-header"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.splitlines()
    committed_body = committed_lines[2:]
    wheel_hash_line = f"    --hash=sha256:{DOCOPT_WHEEL_SHA256}"
    assert committed_body.count(wheel_hash_line) == 1
    committed_without_audited_wheel = [
        line for line in committed_body if line != wheel_hash_line
    ]
    sdist_hash_line = f"    --hash=sha256:{DOCOPT_SDIST_SHA256} \\"
    assert committed_without_audited_wheel.count(sdist_hash_line) == 1
    sdist_index = committed_without_audited_wheel.index(sdist_hash_line)
    committed_without_audited_wheel[sdist_index] = sdist_hash_line.removesuffix(" \\")
    assert committed_without_audited_wheel == generated


def test_audited_docopt_wheel_is_closed_and_self_consistent() -> None:
    raw = DOCOPT_WHEEL.read_bytes()
    assert _sha256(raw) == DOCOPT_WHEEL_SHA256
    with zipfile.ZipFile(io.BytesIO(raw)) as archive:
        names = [member.filename for member in archive.infolist()]
        assert len(names) == len(set(names)) == 6
        assert "docopt.py" in names
        assert "docopt-0.6.2.dist-info/RECORD" in names
        for member in archive.infolist():
            path = PurePosixPath(member.filename)
            mode = member.external_attr >> 16
            assert member.filename and "\\" not in member.filename
            assert not path.is_absolute() and ".." not in path.parts
            assert not member.is_dir()
            assert mode == 0 or stat.S_ISREG(mode)
            archive.read(member)

        assert _sha256(archive.read("docopt.py")) == DOCOPT_MODULE_SHA256
        metadata = archive.read("docopt-0.6.2.dist-info/METADATA").decode("utf-8")
        assert "\nName: docopt\n" in f"\n{metadata}"
        assert "\nVersion: 0.6.2\n" in f"\n{metadata}"

        record_name = "docopt-0.6.2.dist-info/RECORD"
        rows = list(csv.reader(io.StringIO(archive.read(record_name).decode("utf-8"))))
        assert {row[0] for row in rows} == set(names)
        for name, encoded_digest, rendered_size in rows:
            if name == record_name:
                assert encoded_digest == rendered_size == ""
                continue
            payload = archive.read(name)
            algorithm, digest = encoded_digest.split("=", 1)
            expected = base64.urlsafe_b64encode(
                hashlib.sha256(payload).digest()
            ).rstrip(b"=")
            assert algorithm == "sha256"
            assert digest.encode("ascii") == expected
            assert rendered_size == str(len(payload))


def _canonical_json(document: object) -> bytes:
    return (
        json.dumps(
            document,
            ensure_ascii=True,
            allow_nan=False,
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    ).encode("ascii")


def _wheelhouse_document() -> dict[str, object]:
    payload = WHEELHOUSE_MANIFEST.read_bytes()
    document = json.loads(payload)
    assert type(document) is dict
    assert payload == _canonical_json(document)
    return document


def test_runtime_wheelhouse_manifest_is_canonical_and_source_owned() -> None:
    document = _wheelhouse_document()
    assert set(document) == {
        "entries",
        "requirements_sha256",
        "schema_version",
        "target",
        "uv_lock_sha256",
    }
    assert document["schema_version"] == "ava.runtime-wheelhouse/v1"
    assert document["target"] == {
        "implementation": "cpython",
        "platform": "linux_x86_64",
        "python_version": "3.12.13",
    }
    assert (
        document["requirements_sha256"]
        == f"sha256:{_sha256(REQUIREMENTS.read_bytes())}"
    )
    assert document["uv_lock_sha256"] == f"sha256:{_sha256(UV_LOCK.read_bytes())}"

    entries = document["entries"]
    assert type(entries) is list and len(entries) == 144
    assert entries == sorted(entries, key=lambda entry: entry["filename"].encode())
    filenames: list[str] = []
    digests: list[str] = []
    for entry in entries:
        assert type(entry) is dict and set(entry) == {"filename", "sha256"}
        filename = entry["filename"]
        digest = entry["sha256"]
        assert type(filename) is str and release_contract._WHEEL_RE.fullmatch(filename)
        assert type(digest) is str and re.fullmatch(r"sha256:[0-9a-f]{64}", digest)
        filenames.append(filename)
        digests.append(digest)
    assert len(filenames) == len(set(filenames))
    assert len(digests) == len(set(digests))


def _active_runtime_contract() -> tuple[
    dict[tuple[str, str], dict[str, object]],
    dict[str, list[tuple[tuple[str, str], str]]],
]:
    source_contents = {
        "deploy/runtime/wheels/docopt-0.6.2-py2.py3-none-any.whl": (
            DOCOPT_WHEEL.read_bytes()
        )
    }
    (
        details,
        _versions,
        _requirements_projection_sha256,
        _source_pins_sha256,
        source_pins,
        locked_wheels,
    ) = release_contract._runtime_requirements_contract(
        REQUIREMENTS.read_bytes(),
        lock_payload=UV_LOCK.read_bytes(),
        source_contents=source_contents,
        expected_pins={DOCOPT_WHEEL.name: DOCOPT_WHEEL_SHA256},
    )
    candidates: dict[str, list[tuple[tuple[str, str], str]]] = {}
    for identity, wheels in locked_wheels.items():
        for filename, digest in wheels.items():
            candidates.setdefault(filename, []).append((identity, digest))
    for filename, (digest, artifact) in source_pins.items():
        identity = (artifact.name, artifact.version)
        candidates.setdefault(filename, []).append((identity, digest))
    return details, candidates


def test_runtime_wheelhouse_is_the_unique_active_compatible_selection() -> None:
    document = _wheelhouse_document()
    details, candidates = _active_runtime_contract()
    selected: dict[tuple[str, str], str] = {}
    for entry in document["entries"]:
        filename = entry["filename"]
        digest = entry["sha256"]
        matching = [
            (identity, candidate_digest)
            for identity, candidate_digest in candidates.get(filename, [])
            if candidate_digest == digest
        ]
        assert len(matching) == 1
        identity, candidate_digest = matching[0]
        assert candidate_digest in details[identity]["hashes"]
        assert release_contract._marker_applies(str(details[identity]["marker"]))
        tags = release_contract._wheel_filename_tags(filename)
        assert any(release_contract._wheel_tag_compatible(tag) for tag in tags)
        assert identity not in selected
        selected[identity] = filename

    expected = {
        identity
        for identity, requirement in details.items()
        if release_contract._marker_applies(str(requirement["marker"]))
    }
    assert set(selected) == expected
    assert len(selected) == len({name for name, _version in selected}) == 144
    assert selected[("torch", "2.11.0+cpu")].startswith("torch-2.11.0+cpu-")
    assert ("nvidia-ml-py", "13.610.43") in selected
    assert not any(
        name == "triton" or (name.startswith("nvidia-") and name != "nvidia-ml-py")
        for name, _version in selected
    )


def _run_wheelhouse_generator(
    *,
    wheelhouse: Path,
    requirements: Path,
    uv_lock: Path,
    output: Path,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(WHEELHOUSE_GENERATOR),
            "--wheelhouse",
            str(wheelhouse),
            "--requirements",
            str(requirements),
            "--uv-lock",
            str(uv_lock),
            "--output",
            str(output),
        ],
        check=False,
        capture_output=True,
        text=True,
    )


def test_wheelhouse_generator_hashes_only_explicit_offline_inputs(
    tmp_path: Path,
) -> None:
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    first = wheelhouse / "alpha-1.0-py3-none-any.whl"
    second = wheelhouse / "beta-2.0-cp312-cp312-manylinux_2_28_x86_64.whl"
    first.write_bytes(b"alpha wheel\n")
    second.write_bytes(b"beta wheel\n")
    requirements = tmp_path / "requirements.txt"
    uv_lock = tmp_path / "uv.lock"
    output = tmp_path / "manifest.json"
    requirements.write_bytes(b"alpha==1.0 --hash=sha256:placeholder\n")
    uv_lock.write_bytes(b"version = 1\n")

    result = _run_wheelhouse_generator(
        wheelhouse=wheelhouse,
        requirements=requirements,
        uv_lock=uv_lock,
        output=output,
    )
    assert result.returncode == 0, result.stderr
    payload = output.read_bytes()
    document = json.loads(payload)
    assert payload == _canonical_json(document)
    assert (
        document["requirements_sha256"]
        == f"sha256:{_sha256(requirements.read_bytes())}"
    )
    assert document["uv_lock_sha256"] == f"sha256:{_sha256(uv_lock.read_bytes())}"
    assert document["entries"] == [
        {"filename": first.name, "sha256": f"sha256:{_sha256(first.read_bytes())}"},
        {"filename": second.name, "sha256": f"sha256:{_sha256(second.read_bytes())}"},
    ]
    source = WHEELHOUSE_GENERATOR.read_text(encoding="utf-8")
    assert "os.O_NOFOLLOW" in source and "st_nlink != 1" in source
    for forbidden in ("urllib", "requests", "httpx", "socket", "subprocess"):
        assert forbidden not in source


def test_wheelhouse_generator_rejects_non_wheels_links_and_hardlinks(
    tmp_path: Path,
) -> None:
    requirements = tmp_path / "requirements.txt"
    uv_lock = tmp_path / "uv.lock"
    requirements.write_bytes(b"closed requirements\n")
    uv_lock.write_bytes(b"closed lock\n")

    for case in ("extra", "symlink", "hardlink"):
        wheelhouse = tmp_path / case
        wheelhouse.mkdir()
        source = tmp_path / f"{case}-source.whl"
        source.write_bytes(b"wheel payload\n")
        if case == "extra":
            (wheelhouse / "valid-1.0-py3-none-any.whl").write_bytes(b"valid\n")
            (wheelhouse / "README.txt").write_text("extra\n", encoding="utf-8")
        elif case == "symlink":
            (wheelhouse / "linked-1.0-py3-none-any.whl").symlink_to(source)
        else:
            os.link(source, wheelhouse / "linked-1.0-py3-none-any.whl")
        output = tmp_path / f"{case}.json"
        result = _run_wheelhouse_generator(
            wheelhouse=wheelhouse,
            requirements=requirements,
            uv_lock=uv_lock,
            output=output,
        )
        assert result.returncode != 0
        assert not output.exists()


def test_explicit_local_wheelhouse_fixture_regenerates_manifest(tmp_path: Path) -> None:
    fixture = os.environ.get("AVA_RUNTIME_WHEELHOUSE_TEST_FIXTURE")
    if fixture is None:
        pytest.skip("AVA_RUNTIME_WHEELHOUSE_TEST_FIXTURE is not explicitly set")
    output = tmp_path / "regenerated.json"
    result = _run_wheelhouse_generator(
        wheelhouse=Path(fixture),
        requirements=REQUIREMENTS,
        uv_lock=UV_LOCK,
        output=output,
    )
    assert result.returncode == 0, result.stderr
    assert output.read_bytes() == WHEELHOUSE_MANIFEST.read_bytes()
